/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Controlador.ClientesDAO;
import Controlador.Inventario_VentasDAO;
import Controlador.PeliculaDAO;
import Entidades.Inventario_Ventas;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDeepOceanIJTheme;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author C.D.C.A
 */
public class frmIVentas extends javax.swing.JFrame {

    /**
     * Creates new form frmIVentas
     */
    public String FuncionIV;

    public frmIVentas(String fun) {
        this.FuncionIV = fun;
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);

        PeliculaDAO da = new PeliculaDAO();
        da.actualizarComboBoxTipoE();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Realize una venta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel2.setText("CodigoPv:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setText("Proveedor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel13.setText("Pelicula:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 120, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 120, 30));

        jButton2.setForeground(new java.awt.Color(204, 255, 255));
        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, 30));

        jButton3.setForeground(new java.awt.Color(204, 255, 255));
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 90, 30));

        jLabel5.setText("IdCliente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 120, 30));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 30, 30));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 120, 30));

        jLabel6.setText("Unidades:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 120, 30));

        jLabel7.setText("Precio:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 120, 30));

        jLabel8.setText("FechaV:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jDateChooser1MousePressed(evt);
            }
        });
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double Precio = 0;
    
    public void SetDatos(Inventario_Ventas iv) {
        jTextField1.setText(String.valueOf(iv.getCodigoPV()));
        jTextField2.setText(String.valueOf(iv.getIdCliente()));
        jTextField3.setText(iv.getProveedor());
        jTextField4.setText(String.valueOf(iv.getUnidades()));
        jTextField5.setText(String.valueOf(iv.getPrecio()));
        jComboBox1.setSelectedItem(String.valueOf(iv.getPelicula()));
        jDateChooser1.setDate(iv.getFechaV());
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Inventario_VentasDAO iv = new Inventario_VentasDAO();
        if (!jTextField1.getText().equals("")
                && !jTextField2.getText().equals("")
                && !jTextField3.getText().equals("")
                && !jTextField4.getText().equals("")
                && !jTextField5.getText().equals("")) {
            try {
                System.out.println("Si Ejecuta 1");
                int CodigoPv = Integer.parseInt(jTextField1.getText());
                int IdCliente = Integer.parseInt(jTextField2.getText());
                String Pelicula = jComboBox1.getSelectedItem().toString();
                String Proveedor = jTextField3.getText();
                int Unidades = Integer.parseInt(jTextField4.getText());
                Precio = Double.parseDouble(jTextField5.getText());
                Date FechaV = jDateChooser1.getDate();
                System.out.println("Valor de Funcion: " + FuncionIV);
                Inventario_Ventas in = new Inventario_Ventas(CodigoPv, IdCliente, Pelicula, Proveedor, Unidades, Precio, FechaV);
                System.out.println("Valor de Funcion: " + FuncionIV);
                FuncionIV = "Insertar";
                if (FuncionIV.equals("Insertar")) {
                    System.out.println("Si Ejecuta 2");
                    iv.InsertarIventarioV(in);
                    System.out.println("Si Ejecuta 3");
                }
                FuncionIV = "Modificar";
                if (FuncionIV.equals("Modificar")) {
                    System.out.println("Si Ejecuta 4");
                    iv.ModificarIventarioV(in);
                    System.out.println("Si Ejecuta 5");
                    
                }
                frm_Principal.MostrarTabla5();
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese correctamente los datos");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmListaClientes frm = new frmListaClientes();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex() >= 0) {
            jTextField3.setText("DisneyPlus");
            jTextField5.setText(String.valueOf(10));
        }
        if (jComboBox1.getSelectedIndex() >= 1) {
            jTextField3.setText("Studio Ghilbi");
            jTextField5.setText(String.valueOf(12));
        }
        if (jComboBox1.getSelectedIndex() >= 2) {
            jTextField3.setText("Paramount");
            jTextField5.setText(String.valueOf(15));
        }
        if (jComboBox1.getSelectedIndex() >= 3) {
            jTextField3.setText("Netflix");
            jTextField5.setText(String.valueOf(10));
        }
        if (jComboBox1.getSelectedIndex() >= 4) {
            jTextField3.setText("Atres Player");
            jTextField5.setText(String.valueOf(12));
        }
        if (jComboBox1.getSelectedIndex() >= 5) {
            jTextField3.setText("PlutoTV");
            jTextField5.setText(String.valueOf(14));
        }
        if (jComboBox1.getSelectedIndex() >= 6) {
            jTextField3.setText("HBOmax");
            jTextField5.setText(String.valueOf(16));
        }
        if (jComboBox1.getSelectedIndex() >= 7) {
            jTextField3.setText("Fanatiz");
            jTextField5.setText(String.valueOf(15));
        }
        if (jComboBox1.getSelectedIndex() >= 8) {
            jTextField3.setText("Canela Media");
            jTextField5.setText(String.valueOf(12));
        }
        if (jComboBox1.getSelectedIndex() >= 9) {
            jTextField3.setText("BlimTv");
            jTextField5.setText(String.valueOf(14));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jDateChooser1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MousePressed
        // TODO add your handling code here:
        if (jDateChooser1.equals("")) {
            jDateChooser1.setForeground(Color.cyan);
        }
    }//GEN-LAST:event_jDateChooser1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmIVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmIVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmIVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmIVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        try {
            UIManager.setLookAndFeel(new FlatMaterialDeepOceanIJTheme());
//            FlatDarkLaf.setup();
//            IntelliJTheme.setup(frm_Principal.class.getResourceAsStream("/solarized_light_theme.theme.json"));
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIVentas("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
